name: Deploy to Firebase

on:
  push:
    branches:
      - main
    paths:
      - 'baselines/**'
      - 'firebase.json'
      - '.firebaserc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERTEX_CENTER }}'
          projectId: vertex-center
          channelId: live
          target: vertex-baselines
